// users actions
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const ADD_USER = 'ADD_USER';
export const ADD_PROJECTS_TO_DEVELOPER = 'ADD_PROJECTS_TO_DEVELOPER';

// projects actions
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const GET_PROJECTS_LOADING = 'GET_PROJECTS_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_DEVELOPERS_TO_PROJECT = 'ADD_DEVELOPERS_TO_PROJECT';
